export const projects = [
	{
		id: '11',
		name: 'Mobimon',
		imageUrl: '/projects/Mobimon.png',
		description: "Help caregivers monitor patients' mobility metrics remotely",
		languages: ['Java', 'TypeScript', 'Swift'],
		tools: ['AWS', 'Maven', 'XCode'],
		sourceCode: 'https://github.com/UBC-CIC/remote-mobility-monitoring',
		date: new Date(2023, 6 - 1),
		type: ['Software'],
		rating: 9,
	},
	{
		id: '10',
		name: 'Giffy',
		imageUrl: '/projects/Giffy.gif',
		description: 'Share favorite memes and stickers from your phone keyboard',
		languages: ['Java', 'TypeScript', 'SQL'],
		tools: ['Next.js', 'Spring Boot', 'PostgreSQL', 'AWS'],
		sourceCode: 'https://github.com/hungnguyen3/Giffy',
		date: new Date(2023, 5 - 1),
		type: ['Software'],
		rating: 9,
	},
	{
		id: '9',
		name: 'Career Roaster',
		imageUrl: '/projects/Career-Roaster.png',
		description: 'Showcasing your professional skills and receiving constructive feedback',
		languages: ['TypeScript', 'SQL'],
		tools: ['Next.js', 'Node.js', 'PostgreSQL', 'Firebase', 'ChakraUI'],
		sourceCode: 'https://github.com/hungnguyen3/nwHacks2023',
		date: new Date(2023, 1 - 1),
		type: ['Software'],
		rating: 7,
	},
	{
		id: '8',
		name: 'What The Fridge',
		imageUrl: '/projects/What-The-Fridge.png',
		description: 'Solution to managing grocery items & preventing food waste',
		languages: ['TypeScript', 'SQL'],
		tools: ['Next.js', 'Node.js', 'GraphQL', 'PostgreSQL', 'Firebase'],
		sourceCode: 'https://github.com/What-The-Fridge/What-The-Fridge',
		demo: 'https://what-the-fridge.adventurous-hachi.com',
		date: new Date(2022, 2 - 1),
		type: ['Software'],
		rating: 8,
	},
	{
		id: '7',
		name: 'Euphony',
		imageUrl: '/projects/Euphony.avif',
		description: 'Music discovery mobile app',
		languages: ['TypeScript', 'Python'],
		tools: ['React Native', 'Node.js', 'Machine Learning'],
		sourceCode: 'https://github.com/ubclaunchpad/spotify-gen',
		demo: 'https://www.youtube.com/watch?v=78rMSg4dj6I',
		date: new Date(2022, 5 - 1),
		type: ['Software', 'MachineLearning'],
		rating: 9,
	},
	{
		id: '6',
		name: 'Ingredients Decoder',
		imageUrl: '/projects/Ingredient-Decoder.png',
		description: 'Solution to ingredients and nutritional information',
		languages: ['C', 'Python', 'Java', 'JavaScript', 'Verilog'],
		tools: [
			'Raspberry Pi 4',
			'Android Studio',
			'Node.js',
			'MongoDB',
			'FPGA - DE1-SoC',
			'Sonar sensor',
			'Touch screen',
			'Camera',
			'HC-05 chip',
			'ESP-WROOM-02 chip',
		],
		sourceCode: 'https://github.com/hungnguyen3/Ingredient-Decoder',
		demo: 'https://www.youtube.com/watch?v=K5SHd9u0xCo&ab_channel=HungNguyen',
		date: new Date(2021, 4 - 1),
		type: ['Hardware', 'Software'],
		rating: 8,
	},
	{
		id: '5',
		name: 'Lost Pets Finder',
		imageUrl: '/projects/Lost-Pet-Finder.png',
		description: 'An android app that connects people with their lost pets',
		languages: ['JavaScript'],
		tools: ['React Native', 'Node.js', 'MySQL', 'AWS', 'Firebase', 'Jest', 'Codacy', 'Travis CI'],
		sourceCode: 'https://github.com/Lost-Pet-Finder/Lost-Pet-Finder',
		date: new Date(2020, 12 - 1),
		type: ['Software', 'MachineLearning'],
		rating: 8,
	},
	{
		id: '4',
		name: 'SMS School',
		imageUrl: '/projects/SMS-School.png',
		description: 'An online education system for children in developing countries',
		languages: ['TypeScript'],
		tools: ['React', 'Node.js', 'MongoDB', 'Twilio API', 'Bootstrap'],
		sourceCode: 'https://github.com/hungnguyen3/nwHacks',
		date: new Date(2021, 1 - 1),
		type: ['Software'],
		rating: 6,
	},
	{
		id: '3',
		name: 'Dancing Robot',
		imageUrl: '/projects/Dancing-Robot.png',
		description: 'A dancing robot, capable of switching between 6 dance moves',
		languages: ['Python'],
		tools: ['Raspberry Pi 4', 'Servomotors', 'LCD screen', 'Piezzo buzzer', 'RGB lights'],
		sourceCode: '',
		demo: 'https://www.youtube.com/watch?v=zXgueicf6Qo',
		date: new Date(2019, 12 - 1),
		type: ['Hardware', 'Software'],
		rating: 7,
	},
	{
		id: '2',
		name: 'Line Tracking Robot',
		imageUrl: '/projects/Line-Tracking-Robot.png',
		description: 'An autonomous robotic vehicle',
		languages: ['Python'],
		tools: ['Raspberry Pi 4', 'Servomotors', 'LCD screen', 'distance sensors', 'RP4 camera'],
		sourceCode: '',
		demo: 'https://www.youtube.com/watch?v=RC4f2ZNXzzs&t=6s/&ab_channel=HungNguyen',
		date: new Date(2020, 3 - 1),
		type: ['Hardware', 'Software'],
		rating: 8,
	},
	{
		id: '1',
		name: 'Finding Cherries',
		imageUrl: '/projects/Finding-Cherries.png',
		description: 'A 2D game with classic Mario style',
		languages: ['C#'],
		tools: ['Unity', 'Adobe Photoshop'],
		sourceCode: '',
		demo: 'https://simmer.io/@hunglnl1/bear-finds-home/',
		date: new Date(2020, 9 - 1),
		type: ['GameDev'],
		rating: 7,
	},
];

export type ElementType<T extends ReadonlyArray<unknown>> = T extends ReadonlyArray<infer ElementType>
	? ElementType
	: never;

export type Project = ElementType<typeof projects>;
